@startuml

title Customer registration

actor Customer as c
actor Representative as re
actor Mailman as m
actor Registrar as r
actor Bookkeeper as b

c -->> re: provides registration data
re -->> b: register this customer
b -->> b: checks if email exists
alt email exists
b -->> m: send mail to this address that we already have it
else non-existing email
b --> r: register new account with this data
r -->> r: generates new internal id
r -->> r: registers customer
r -->> m: send mail to this address that he can use our services
end
m -->> c: sends mail

@enduml
